### PR TITLE
bengali language support added

### PR DESCRIPTION
**Pull request by Xatta-Trone**

### CODE REVIEW

**Comment by octokatherine** [comment]
@Xatta-Trone can you resolve conflicts?

**Comment by Xatta-Trone** [comment]
I have resolved the file conflicts, but it seems there is a problem with package-lock.json file due to further changes made by other users.

**Comment by Xatta-Trone** [comment]
> 
> 
> @Xatta-Trone can you resolve conflicts?

I have resolved the file conflicts, but it seems there is a problem with package-lock.json file due to further changes made by other users.

**Comment by Xatta-Trone** [comment]
> 
> 
> @Xatta-Trone can you resolve conflicts?

I have resolved the file conflicts.

**Pull request merged**
