### PR TITLE
✨ Added progress bar while navigating

### PR DESCRIPTION
**Pull request by max-programming**
Check the deployed PR, click the button to navigate to diff page, and now there is a progress bar at the top so that the user knows they are navigating and they don't click the button continuously

### CODE REVIEW

**Comment by max-programming** [comment]
@jose-vale Can you please check this PR and let me know if something is missing?

**Comment by jose-vale** [comment]
> @jose-vale Can you please check this PR and let me know if something is missing?

Really cool addition, and the code looks good to me. A possible improvement to consider would be to get the emerald color from tailwind instead of hard coding it (see attached image).
Don't know if @octokatherine has any other feedback.

image

**Comment by max-programming** [comment]
> > @jose-vale Can you please check this PR and let me know if something is missing?
> 
> Really cool addition, and the code looks good to me. A possible improvement to consider would be to get the emerald color from tailwind instead of hard coding it (see attached image and side note).
> Don't know if @octokatherine has any other feedback.
> 
> image
> 
> Side Note: Keeping in mind what is discussed in the [docs](https://tailwindcss.com/docs/configuration#referencing-in-java-script) regarding bundle size, this might need further consideration.

Thanks for the reply Jose! I guess this way is easier than importing the config and resolving it.
image

**Comment by max-programming** [comment]
Done with the small fix! Ready to merge

**Pull request merged**
