### PR TITLE
Updating the sections column to be collapsible

### PR DESCRIPTION
**Pull request by allister-grange**
I'm not too sure if you will enjoy the styling, please let me know what you think!

Animation is tricky as you don't know the length of the expanded accordion and I didn't want to do anything janky like hardcode a height of 1600px. If you don't see the length of the sections changing much and would prefer animation over hardcoding the height, let me know.

#133

### CODE REVIEW

**Comment by octokatherine** [comment]
@allister-grange it looks pretty good, I think it might be better if the "Show default sections" was styled differently than the section buttons so it's clear that it's not a section itself

**Comment by allister-grange** [comment]
@octokatherine I centred the text and bolded it to match with the "Custom Section" button, do you prefer this?

**Comment by octokatherine** [comment]
I'm wondering if this addresses the initial request in the issue https://github.com/octokatherine/readme.so/issues/133 which asked for a dropdown for accessibility. I think making it collapsable alone doesn't improve the accessibility, we would have to make it an actual html dropdown (keyboard shortcuts and stuff behave differently in a dropdown.) But I'm not sure I want to go down that path UI wise

**Comment by allister-grange** [comment]
Well, if you like the look/feel of this collapsible section, it's there for you to use!

No worries if it's not wanted 🙂

Let me know if you wan anything more from me

**Pull request closed without merging**
