### PR TITLE
#4 Feat mobile 📱  responsive 🧐

### LINKED ISSUE #4: Make site responsive for mobile
Currently, on any touch devices, when you navigate to the editor it just shows a message saying that this site is optimized for desktop.

### PR DESCRIPTION
**Pull request by Rishabh-Rathod**
Changes

- [x] Add Header with menu options to toggle drawer.
- [x] Add Drawer containing `sections`.
- [x] Fix `section` item's drag and drop functionality for mobile.
- [x] limit maxWidth of PreviewColumn to avoid its overflow outside the viewport.
- [x] Implement Tabs to show column selection in mobile.
- [x] Replace monaco Editor to simple text Editor for mobile.
- [x] Add download button 

Resolves #4

### CODE REVIEW

**Comment by Rishabh-Rathod** [comment]
Monaco editor also has copy paste issue for mobile didn't test that before.

That seems to me a very important feature to have will replace it with simple text editor.

**Comment by Rishabh-Rathod** [comment]
For Editor as the usecase is only for a markdown editor. Was something like https://github.com/andrerpena/react-mde
considered?
@katherinepeterson

**Comment by katherinepeterson** [comment]
@Rishabh-Rathod I think the download button could either be in the Nav to the left of the hamburger icon, or at the top of the drawer menu. What do you think?

**Comment by Rishabh-Rathod** [comment]
@katherinepeterson Download icon without text should be fine beside the hamburger icon according to me. Will add that.

Let me know if i need to make any other changes in the PR before review.

**Comment by Rishabh-Rathod** [comment]
### Screenshot 
image

- [x] Add `Download` button. ( Done ✅  )
 
All major tasks for mobile responsive seems to be completed according to me, @octokatherine can you review once and let me know if there is any changes needed or if something was missed.

> I have only tested for android devices.

**Comment by octokatherine** [comment]
Hi @Rishabh-Rathod, sorry I've been busy and it took me a bit to get back to this, but this looks great!! 

Do you mind just resolving the conflicts? Then I'll merge!

**Comment by Rishabh-Rathod** [comment]
> Hi @Rishabh-Rathod, sorry I've been busy and it took me a bit to get back to this, but this looks great!!
> 
> Do you mind just resolving the conflicts? Then I'll merge!

No issues, I can understand better as we both have joined a new company recently 🤓. 
I have resolved merge conflicts 😁
@octokatherine

**Review by octokatherine — APPROVED** [review]

**Pull request merged**
